### 
GET http://localhost:3000/links/d9LPO/stats  HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/links HTTP/1.1
Content-Type: application/json

{
  "url":"https://www.luiztools.com.br"
}

###
PUT http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
      
}
###
DELETE http://localhost:3000/users HTTP/1.1
Content-Type: application/json
