### 
GET http://localhost:3001/links/lDQ6P HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3001/links HTTP/1.1
Content-Type: application/json

{
  "url":"https://www.luiztools.com.br"
}

###
PUT http://localhost:3001/users HTTP/1.1
Content-Type: application/json

{
      
}
###
DELETE http://localhost:3001/users HTTP/1.1
Content-Type: application/json
